--insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Title','Publisher/Author','GRL,'Box #,#books','Min. Level','Max. Level','Words',keywords','Series');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Baby','Rigby',1,1,11,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Balloons','Rigby',1,1,8,1,1,57,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Play','Rigby',1,1,14,1,1,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Up in the sky','Rigby',1,1,11,1,1,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Fruit Salad','Literacy Tree',1,2,22,1,1,23,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ouch!','Rigby',1,2,32,1,1,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Are You?','Literacy Tree',1,2,24,1,1,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who Likes Ice Cream','Rigby',1,2,25,1,1,15,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the Garden','Rigby PM Plus',1,3,11,1,1,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Look at the house','Rigby PM Plus',1,3,13,1,1,53,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going on Vacation','Rigby PM Plus',1,4,17,1,1,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I am running','Rigby PM Plus',1,4,10,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We dress up','Rigby',1,4,11,1,1,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Here''s a House','Wright Group',1,5,7,1,1,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Naughty Kitten','Rigby Smart Start',1,5,3,1,1,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Farm','Rigby Smart Start',1,5,5,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Farm','Literacy Tree',1,5,22,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the shopping cart','Rigby',1,6,9,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Little things','Rigby',1,6,16,1,1,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Amazing Race','Rigby',1,6,7,1,1,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Time for dinner','Rigby Smart Start',1,6,7,1,1,15,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Dog Day','Rigby Smart Start',1,7,1,1,1,23,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going to School','Rigby',1,7,6,1,1,21,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the Supermarket','Rigby',1,7,8,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Planet','Rigby',1,7,6,1,1,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Robot','Rigby Smart Start',1,7,5,1,1,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Treasure Hunt','Rigby',1,7,9,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Under the Bed','Rigby Smart Start',1,7,7,1,1,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What A Mess','Rigby',1,7,6,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Zoo','Literacy Tree',1,8,20,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Royal Family','Seedling Pub',1,8,6,1,2,17,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where is Gabby?','Pioneer Valley',1,8,4,1,1,21,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dad','Rigby PM Collection',1,9,13,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Deep in the Forest','Houghton Mifflin',1,9,5,1,1,0,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Me','Rigby PM Collection',1,9,9,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Mom','Rigby PM Collection',1,9,13,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Moms and Dads','Rigby',1,9,12,1,1,36,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In our classroom','Rigby PM,',1,10,7,1,1,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Playing','Rigby',1,10,9,1,1,39,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Splash','Wright Group',1,10,4,1,1,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Baby Animals at Home','Wright Group',1,11,4,1,2,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Christmas','Rigby Smart Start',1,11,8,1,1,16,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Like Balloons','Dominie ,',1,11,3,2,2,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Read','Dominie ,',1,11,5,2,2,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('James is Hiding','Windmill Books',1,11,2,1,1,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Class','Seedling Pub',1,11,14,1,2,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Our School','Houghton Mifflin',1,11,3,1,2,12,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Surprise Inside','Houghton Mifflin',1,11,6,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Winter Fun','Dominie ,',1,11,2,1,1,13,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Rosie Likes Pink','Pioneer Valley',1,12,6,1,1,24,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dinner Time for Bella and Rosie','Pioneer Valley',1,12,6,1,1,31,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Looking Out','Pioneer Valley',1,12,6,1,1,27,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dressing-Up','Rigby PM Starters One',1,12,24,1,1,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Pets','Rigby',1,12,8,1,1,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A House','Rigby',1,13,16,1,1,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Glasses','Dominie Press',1,13,6,1,1,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('On the Line','Dominie Press',1,13,6,1,1,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Can Paint','Wright Group',1,14,2,1,1,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Car Ride','Sundance',1,14,8,1,1,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Circus Train','Sundance',1,14,8,1,1,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('When The Circus Comes To Town','Sundance',1,14,9,1,1,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Box','Rigby',1,15,7,1,1,30,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Snowman','Rigby',1,15,1,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Socks','Rigby',1,15,8,1,1,21,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Clown','Rigby Smart Start',1,15,8,1,1,13,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Weather','Rigby',1,15,9,1,1,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Did Ben Want?','Rigby',1,15,8,1,1,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where Is My Pet?','Rigby',1,15,8,1,1,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Big things','Rigby PM,',1,16,11,1,1,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Look at Pickles','Pioneer Valley',1,16,12,2,2,29,null,'Pickles');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bella''s Busy Day','Pioneer Valley',1,17,6,2,2,36,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Snow Fun','Pioneer Valley',1,17,6,2,2,37,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Playing Together','Pioneer Valley',1,17,6,2,2,66,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Food for Jasper','Pioneer Valley',1,17,6,2,2,28,null,'Jasper the Cat');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where are the babies?','Rigby PM,',1,18,51,2,2,81,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Cat and Mouse','Rigby PM,',1,19,43,2,2,75,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ball games','Rigby',1,20,45,2,2,88,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Climbing','Rigby PM,',1,21,9,2,2,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('One Day','Dominie Press',1,22,5,2,2,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Recess','Dominie Press',1,22,6,2,2,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Ball Game','Literacy 2000,',1,22,4,2,2,16,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The skier','Rigby',1,22,13,2,2,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Too Much','Dominie Press',1,22,3,2,2,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Two Plus Two','Dominie Press',1,22,4,2,2,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We go out','Rigby PM,',1,22,7,1,1,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Stop!','Rigby',1,23,42,2,2,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('After the Rain','Literacy Tree',1,24,13,2,2,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I am Climbing','Literacy Tree',1,24,18,2,2,22,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the Sand','Literacy Tree',1,24,15,2,2,39,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Machine','Literacy Tree',1,24,19,2,2,30,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Treasure Hunt','Literacy Tree',1,24,14,2,2,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The rock pools','Rigby PM,',1,25,55,2,2,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Big and Little','Rigby',1,26,11,2,2,68,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Clothes','Rigby',1,26,16,2,2,36,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Little Cat','Rigby',1,26,13,2,2,57,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Toy Box','Rigby PM Plus',1,26,6,2,2,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Up and Down','Rigby PM Plus',1,26,4,2,2,81,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Catching','Dominie Press',1,27,7,2,2,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Colors In the City','Kaeden Group',1,27,2,2,2,61,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Eating','Wright',1,27,6,2,2,29,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Can Make Music','Sundance',1,27,7,2,2,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Off to Work','Literacy 2000,',1,27,2,2,2,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Clown','Kaeden Group',1,27,4,2,2,29,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The shopping mall','Rigby PM,',1,27,9,2,2,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Can Fly','Literacy 2000,',1,27,2,2,2,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Happy Holidays','Dominie Press',1,28,5,2,2,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who Reads?','Dominie Press',1,28,6,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who''s Coming for a Ride?','Literacy 2000,',1,28,5,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sally''s new shoes','Rigby PM,',1,29,44,2,2,58,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Packing my bag','Rigby PM,',1,30,40,2,2,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Pencil','Rigby',1,31,41,2,2,97,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ben''s Red Car','Rigby',1,32,52,2,2,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Blue Day','Literacy Tree',1,33,35,2,3,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Camping','Literacy Tree',1,33,19,2,2,19,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who''s Coming for a Ride?','Literacy 2000,',1,33,28,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Follow the leader','Windmill Books',1,34,3,2,2,15,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Rain','Dominie ,',1,34,2,2,2,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Too Much','Dominie Press',1,34,4,2,2,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where Are the Car Keys','Windmill Books',1,34,5,2,2,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where Can Kitty Sleep?','Windmill Books',1,34,3,2,2,15,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who Wears This Hat','WrightGroup',1,34,7,2,2,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Party Hats','Rigby',1,35,15,2,2,72,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Playing Outside','Rigby',1,35,12,2,2,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Parade','Rigby PM plus',1,35,14,2,2,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Big Sea Animals','Rigby',1,36,12,2,2,79,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going Out','Rigby',1,36,14,2,2,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Sand Castle','Rigby',1,36,15,2,2,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Little Seed','Rigby',1,37,8,2,2,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Books','Rigby',1,37,9,2,2,21,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dinosaur Party','Rigby',1,37,8,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the Bathroom','Rigby',1,37,8,2,2,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Iron Horse','Rigby',1,37,8,2,2,21,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Model','Rigby',1,37,8,2,2,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Robber','Rigby',1,37,8,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Out in the weather','Rigby PM,',1,38,48,2,2,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Show and Tell','Literacy Tree',1,39,18,2,2,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Race','Windmill Books',1,39,5,2,2,54,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Surprise Party','Literacy Tree',1,39,12,2,2,85,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dressing Up','Rigby Smart Start',1,40,9,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hide and seek','Rigby Smart Start',1,40,6,2,2,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Home','Rigby',1,40,9,2,2,23,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('On the Beach','Rigby',1,40,6,3,3,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Animals Went to Bed','Rigby',1,40,8,2,2,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Puzzle','Rigby Smart Start',1,40,7,2,2,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Boat Ride','PM Stars',1,41,12,2,3,38,null,'Little Teddy');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Big Hole','PM Stars',1,41,12,2,3,39,null,'The Toy Town');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dad''s Ship','PM Stars',1,41,12,2,3,42,null,'Ben');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sally and the Leaves','PM Stars',1,42,12,2,3,55,null,'Sally');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hello, Bingo!','PM Stars',1,42,12,2,3,42,null,'Sam and Bingo');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sally and the Elephant','PM Stars',1,42,12,2,3,50,null,'Sally');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Look at me','Rigby',1,43,13,2,2,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The way I go to school','Rigby',1,43,11,2,2,53,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Yummy Lunch','Pioneer Valley',1,44,1,2,2,22,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Gabby Goes Up and Down','Pioneer Valley',1,44,6,2,2,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Gabby Visits Buster','Pioneer Valley',1,44,5,2,2,55,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Over the Bridge','Sundance',1,44,13,2,2,50,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We went To The Zoo','Sundance',1,44,7,2,2,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Don''t Wake the Baby','Literacy Tree',1,45,28,2,2,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Scrumptious Sundae','Literacy Tree',1,45,9,2,2,17,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Giant''s Breakfast','Literacy Tree',1,45,32,2,2,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dreaming','Rigby',1,46,7,2,2,23,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Our House','Literacy Tree',1,46,17,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Bath','Rigby Smart Start',1,46,1,2,2,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At the Zoo','Rigby',1,47,8,2,2,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The go-carts','Rigby',1,47,11,2,2,46,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Time for dinner','Rigby PM Collection',1,47,12,2,2,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('All of Me','Literacy 2000,',1,48,4,2,2,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dear Santa','Literacy Tree',1,48,30,2,2,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Jack-o-lantern','Twig Books',1,48,4,2,2,37,'Autumn',null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Our Baby','Literacy Tree',1,48,27,2,2,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Jack''s Road','PM Stars',1,49,12,2,3,59,null,'Jack and Billy');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Matthew and Emma','PM Stars',1,49,12,2,3,49,null,'Matthew and Emma');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bubbles in the Sky','PM Stars',1,49,12,2,3,57,null,'Max and Grandpa');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We can run','Rigby PM,',1,50,46,3,3,77,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Monkey''s Friends','Literacy Tree',1,51,11,3,3,36,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Little Chimp','Rigby PM,',1,51,12,3,3,52,null,'Little Chimp');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Big Bone','Pioneer Valley',1,51,6,3,3,78,null,'Jack and Daisy');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Teddy Bear''s Picnic','PM Stars',1,51,12,3,3,66,null,'Little Teddy');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Like','Literacy Tree',1,52,17,3,3,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Teeny Tiny Tina','Literacy 2000,',1,52,28,3,3,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Fishing','Rigby',1,53,30,3,3,63,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Birthday Cake for Ben','Rigby',1,53,20,3,3,71,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Animals','Rigby Smart Start',1,54,7,3,3,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Be Quiet','Rigby',1,54,8,3,3,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Breakfast for Pickles','Pioneer Valley',1,54,12,3,3,62,null,'Pickles');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Lost!','Rigby',1,54,8,3,3,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Spooky Pet','Rigby',1,54,9,3,3,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Tim''s Paintings','Rigby',1,54,6,3,3,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Four ice creams','Rigby',1,55,39,3,3,61,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Sun and the Moon','PM Stars',1,55,12,2,3,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The photo book','Rigby PM,',1,55,20,3,3,76,null,'Kate, James, and Nick');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Looking down','Rigby',1,56,35,3,3,70,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going to Work','Literacy Tree',1,57,24,3,4,58,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Jump into Bed','Literacy Tree',1,57,18,3,4,51,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Oh, Fiddlesticks!','Literacy Tree',1,57,5,3,3,60,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Our Shadows','Literacy Tree',1,57,20,3,3,54,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Accident','Rigby',1,58,47,3,3,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At the Farm','Sundance',1,59,16,3,3,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At the Zoo','Sundance',1,59,5,3,4,73,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In My Bed','Literacy Tree',1,59,27,3,4,57,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('On Our Street','Sundance',1,59,6,3,4,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Shopping','Sundance',1,59,10,3,4,78,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Nests','Wright Group',1,60,4,3,3,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('New Shoes','WrightGroup',1,60,9,3,3,29,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('One Bee Got on the Bus','Ready Readers',1,60,5,3,4,43,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sally and the Daisy','Rigby',1,60,31,3,3,60,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('That Fly','Ready Readers',1,60,6,3,3,26,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What''s the Time, Mr. Wolf?','Rigby',1,60,6,3,3,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bath Time','Wright Group',1,61,10,3,3,23,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Fun in the Snow','Footprints',1,61,11,3,3,56,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Getting There','Wright Group',1,61,5,3,3,36,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going to the Beach','Sundance',1,61,4,3,4,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('On Safari','Rigby',1,61,5,3,3,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What I Like at School','Sundance',1,61,4,3,4,64,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Places','Sundance',1,61,8,3,4,88,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Places','Dominie Collection',1,61,5,3,4,76,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Baby Lamb''s first drink','Rigby PM,',1,62,27,3,3,64,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Frogs Can Jump','The Wright Group',1,62,6,3,3,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sam and Bingo','Rigby',1,62,2,3,3,53,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sam''s Balloon','Rigby',1,62,2,3,3,54,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Can you see the eggs','Rigby PM,',1,63,38,3,3,87,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Champions','Twig Books',1,64,8,3,3,13,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Don''t Leave Anything Behind!','Rigby',1,64,26,3,3,22,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Grocery Shopping','Kaeden Group',1,64,3,3,3,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Under My Bed','Literacy 2000,',1,64,6,3,3,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Cat Food','Rigby',1,65,19,3,3,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Little Dog','Literacy Tree',1,65,19,3,3,102,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The little snowman','Rigby PM,',1,65,14,3,3,59,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The big kick','Rigby PM,',1,66,25,3,3,67,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Wake Up, Dad','Rigby PM,',1,66,28,3,3,67,null,'Kate, James, and Nick');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hat Trick','Literacy Tree',1,67,33,3,3,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Can Do It Myself','Literacy Tree',1,67,30,3,3,37,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dressing Up','Literacy 2000,',1,68,34,3,3,31,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Here''s What I Made','Literacy 2000,',1,68,33,3,3,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Row Your Boat','Rigby',1,68,4,3,4,18,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Too Many Clothes','Literacy Tree',1,68,14,3,3,31,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Did Kim Catch?','Rigby',1,68,31,3,4,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Filbert The Fly','Literacy Tree',1,69,10,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Getting Ready for the Ball','Literacy Tree',1,69,20,3,3,27,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Spy','Literacy Tree',1,69,21,3,3,25,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In Went Goldilocks','Literacy Tree',1,69,21,3,4,30,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Mud Pie','Literacy Tree',1,69,17,3,4,14,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sharing','Literacy Tree',1,69,16,3,3,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The baby owls','Rigby PM,',1,70,23,3,4,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The lazy pig','Rigby PM,',1,70,18,3,3,78,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Tiger, Tiger','Rigby',1,71,20,3,3,55,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Climbing','Literacy Tree',1,72,32,3,3,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hedgehog is hungry','Rigby ,',1,72,21,3,3,76,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who Ate the Lettuce?','Literacy Tree',1,72,19,3,3,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Woof','Literacy Tree',1,72,34,3,3,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Cat and Mouse','Literacy Tree',1,73,19,3,3,62,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Giant''s Day Out','Rigby',1,73,8,3,3,26,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hot dogs','Rigby PM,',1,74,20,3,4,84,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The merry-go-round','Rigby PM,',1,74,32,3,3,84,null,'Kate, James, and Nick');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My little dog','Rigby PM,',1,75,43,3,3,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Photo time','Rigby',1,76,16,3,3,59,null,'Jack and Billy');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Pet Parade','Literacy Tree',1,76,8,3,3,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The flower girl','Rigby PM,',1,76,24,3,4,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Animals At the Zoo','Sprouts',1,'76a',12,3,3,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bags, Cans, Pots, and Pans','Ready Readers',1,'76a',6,3,4,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ben''s Pets','Ready Readers',1,'76a',6,3,4,30,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Baby in the Cart','Wright Group',1,'76b',4,3,3,84,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Shadow','Ready Readers',1,'76b',6,3,4,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Is It?','Sprout',1,'76b',13,3,3,31,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Six Go By','Modern Curr. Press',1,'76c',6,3,4,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('When It Rains','Dominie Collection',1,'76c',5,3,4,37,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We Went To The Movies','Sprout',1,'76c',12,3,3,26,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Buster','Twig',1,'76c',5,3,4,36,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Barn Dance','Wright Group',1,77,4,3,4,47,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('How to Make a Hot Dog','Wright Group',1,77,3,3,4,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Kitty and the birds','Rigby PM,',1,77,23,3,3,64,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At the Library','Rigby',1,78,43,3,3,69,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hungry Kitten','Dominie Press',1,78,4,3,4,50,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What I Left on My Plate','Dominie Press',1,78,6,3,4,54,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Raindrop','Dominie Press',1,'78a',6,3,4,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('All About Dinosaurs','Dominie Press',1,'78a',2,3,4,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Can Taste','Dominie Press',1,'78a',7,3,4,31,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Lots of Dogs','Dominie Press',1,'78a',7,3,4,68,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Pumpkin','Dominie Press',1,'78a',6,3,4,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('On The Road','Dominie Press',1,'78a',6,3,4,47,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Picnic','Dominie Press',1,'78a',4,3,4,48,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Doctor Boondoggle','Wright Group',1,'78b',5,3,4,52,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('First and Last','Dominie Press',1,'78b',5,3,4,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('How to Make Can Stilts','Wright Group',1,'78b',5,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hungry Kitten','Dominie Press',1,'78b',6,3,4,50,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Can Read','Dominie Press',1,'78b',5,3,4,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I See','Dominie Press',1,'78b',2,3,4,29,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Levi Sings','Dominie Press',1,'78b',5,3,4,29,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Little Hearts','Wright Group',1,'78b',5,3,4,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Big Barn','Dominie Press',1,'78b',5,3,4,81,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Winter Fun','Dominie Press',1,'78b',6,3,4,13,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Yes, I Can','Dominie Press',1,'78b',7,3,4,30,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Mae-Nerd','Dominie Press',1,'78c',6,3,4,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Merry-Go-Round','Dominie Press',1,'78c',6,3,4,66,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Noises','Dominie Press',1,'78c',7,3,4,98,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ready for School','Dominie Press',1,'78c',6,3,4,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('What Did They Want?','Rigby',1,'78c',8,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Dressing-Up Box','Wright',1,'78c',4,3,4,61,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bedtime','Rigby PM Plus',1,79,1,4,4,83,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Happy Birthday','Literacy Tree',1,79,21,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hungry Bear','Rigby',1,79,3,3,4,22,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Magic Food','Rigby',1,79,8,3,4,26,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Time for Bear','Rigby',1,79,2,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Time for Bed','Rigby Smart Start',1,79,3,3,4,28,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Fast, Faster, Fastest','Twig Books',1,80,7,4,4,66,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Move it','Wright Group',1,80,9,4,4,58,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The Fox','Owen Publishers',1,80,7,4,4,24,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bubbles','Literacy 2000,',1,81,4,3,4,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Gabby is Hungry','Pioneer Valley',1,81,6,4,4,78,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Kittens','Literacy Tree',1,81,21,4,4,22,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('If You''re Happy','Literacy Tree',1,82,17,4,4,179,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In the Garden','Rigby',1,82,35,4,4,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Amy Goes to School','Literacy Tree',1,83,42,4,4,90,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hot Potato and Cold Potato','Wright Group',1,84,5,4,4,77,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Am a Cat','Literacy Tree',1,84,2,4,4,65,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Let Me In','Literacy Tree',1,84,17,4,4,115,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Hide and Seek','Rigby PM ,',1,85,21,4,4,108,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Tom is brave','Rigby PM,',1,85,26,4,4,57,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Grandma''s House','Pioneer Valley',1,86,6,4,4,113,null,'Jasper the Cat');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Little Chimp and Big Chimp','Rigby PM,',1,86,12,4,4,66,null,'Little Chimp');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Jasper the Fat Cat','Pioneer Valley',1,86,6,4,4,68,null,'Jasper the Cat');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Balloons go Pop!','PM Stars',1,86,12,4,4,74,null,'Kate, James, and Nick');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Screech!','Rigby Literacy Tree',1,87,38,4,4,41,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('When I Pretend','Literacy Tree',1,87,30,3,4,40,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Trucks','Literacy Tree',1,87,5,3,4,38,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('In My Room','Literacy 2000,',1,88,21,4,4,44,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The farm in spring','Rigby',1,89,43,4,4,77,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At the Park','Sundance',1,90,6,4,5,91,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Bella''s Birthday','Footprints',1,90,12,4,4,61,null,'Bella and Rosie');
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going to Grandpa''s House','Kaeden Group',1,90,4,4,4,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Greedy Cat is Hungry','Cowley',1,90,8,4,4,103,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('I Like Painting','Sundance',1,90,7,4,4,68,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Sssh!','Wright Group',1,90,5,4,4,49,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('A Bear Lived In A Cave','Sundance',1,90,2,4,5,102,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going To McDonald''s','FCPS,',1,91,12,4,4,43,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('At The Pool','Wright Group',1,92,5,4,4,64,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Blackberries','Rigby',1,92,17,4,4,107,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Breakfast','Wright Group',1,92,5,3,4,35,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Mrs. Cook''s Hats','Kaeden Group',1,92,5,4,4,31,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My Dream','Oxford',1,92,6,3,4,34,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The grab bag','Rigby PM,',1,92,1,4,4,85,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ben''s treasure hunt','Rigby',1,93,28,4,4,102,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The bumper cars','Rigby PM,',1,93,15,4,4,94,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Dan, The Flying Man','Shortland Publication',1,93,2,4,4,60,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('We like fish','Rigby',1,94,50,4,4,109,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Who Helps You?','Sprouts',1,95,12,4,4,33,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Friends','Sprouts',1,96,12,4,4,42,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Snow Walk','Dominie ,',1,97,4,5,6,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('You Can Play Soccer','Sprouts',1,97,12,4,4,37,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Splash','FCPS,',1,98,12,4,4,32,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('The hungry kitten','Rigby PM,',1,98,9,4,4,95,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Ben''s Teddy Bear','Rigby',1,99,23,5,5,68,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Going Shopping','Sprout',1,99,12,4,5,45,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Happy Face, Sad Face','Wright Group',1,100,6,4,5,76,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Lizard loses his tail','Rigby PM,',1,100,25,4,4,54,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Mumps','Rigby PM,',1,101,15,4,4,112,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Our Dog Sam','Literacy 2000,',1,101,24,4,4,56,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Take, a Bow, Jody','Seedling Pub',1,102,5,5,6,78,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Father Bear goes fishing','Rigby PM,',1,'102a',20,4,4,98,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('Where are the sunhats?','Rigby PM,',1,'102a',25,4,4,130,null,null);
insert into book (title, author, color, box, copy_count, minlevel, maxlevel, word_count, keyword, series_tmp) values ('My New Bike','FCPS,',1,103,12,4,5,33,null,null);

